import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/** Toast provider for app-wide notifications */}
        {/** eslint-disable-next-line @next/next/no-head-element */}
        <div>
          {/* Client boundary inside body */}
          {/* @ts-expect-error Server/Client interop fine for provider wrapper */}
          <ClientToast>{children}</ClientToast>
        </div>
      </body>
    </html>
  );
}

// Small client wrapper to host the ToastProvider in the app shell
function ClientToast({ children }: { children: React.ReactNode }) {
  // Dynamic import avoided; simple re-export
  const { ToastProvider } = require('@/lib/ui/ToastProvider');
  const { SessionExpiredListener } = require('@/app/components/SessionExpiredListener');
  const HeaderBar = require('@/app/components/HeaderBar').default;
  const pos = process.env.NEXT_PUBLIC_TOAST_POSITION || 'top-right';
  const dur = Number(process.env.NEXT_PUBLIC_TOAST_DURATION || 3000);
  return (
    <ToastProvider position={pos} defaultDuration={isNaN(dur) ? 3000 : dur}>
      <HeaderBar />
      <SessionExpiredListener />
      {children}
    </ToastProvider>
  );
}
